version: '3'
services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: foyer  # Change to your desired database name
      MYSQL_USER: root       # Use your specified user
      MYSQL_PASSWORD: root_password  # Use your specified password
      MYSQL_ROOT_PASSWORD: root_password  # Use your specified root password
    ports:
      - "3306:3306"
    networks:
      - app-network

  app:
    image: parkchanyeolnour/foyer-app:latest  # Use your custom image here
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/foyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_password

    ports:
      - "8082:8082"  # Adjust the port if necessary
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
